"""Generate PATH shim wrappers and manage the one-time PATH profile entry."""

from __future__ import annotations

from pathlib import Path

from anon_proxy.routing.state import home_dir

PATH_MARKER = "# added by anon-proxy"

_SHIM_TEMPLATE = """#!/bin/sh
# anon-proxy routing shim for {command}. Do not edit; regenerated by the app.
CMD={command}
SHIM_DIR=${{0%/*}}
[ "$SHIM_DIR" = "$0" ] && SHIM_DIR=.
SHIM_DIR=$(CDPATH= cd -- "$SHIM_DIR" && pwd)
FRAG="${{ANON_PROXY_HOME:-$HOME/.anon-proxy}}/env.d/{command}.sh"
[ -f "$FRAG" ] && . "$FRAG"
REAL=
OLDIFS=$IFS
IFS=:
FIRST=1
for d in $PATH; do
  if [ "$FIRST" = 1 ]; then
    FIRST=0
    [ -x "$d/$CMD" ] && continue
  fi
  [ "$d" = "$SHIM_DIR" ] && continue
  [ "$d/$CMD" = "$SHIM_DIR/$CMD" ] && continue
  [ "$d/$CMD" -ef "$SHIM_DIR/$CMD" ] 2>/dev/null && continue
  if [ -x "$d/$CMD" ]; then REAL="$d/$CMD"; break; fi
done
IFS=$OLDIFS
[ -n "$REAL" ] || {{ echo "anon-proxy: real '$CMD' not found on PATH" >&2; exit 127; }}
exec "$REAL" "$@"
"""


def shim_dir() -> Path:
    return home_dir() / "bin"


def render_shim(command: str) -> str:
    return _SHIM_TEMPLATE.format(command=command)


def install_shim(command: str) -> Path:
    d = shim_dir()
    d.mkdir(parents=True, exist_ok=True)
    path = d / command
    path.write_text(render_shim(command))
    path.chmod(0o755)
    return path


def remove_shim(command: str) -> None:
    (shim_dir() / command).unlink(missing_ok=True)


def path_snippet() -> str:
    return f'export PATH="{shim_dir()}:$PATH"  {PATH_MARKER}\n'


def install_path_entry(profile: Path) -> bool:
    # encoding pinned: the packaged app runs under an ASCII default locale, so a
    # bare read_text() crashes on any non-ASCII byte in the user's profile.
    text = profile.read_text(encoding="utf-8") if profile.exists() else ""
    if PATH_MARKER in text:
        return False
    if text and not text.endswith("\n"):
        text += "\n"
    profile.write_text(text + path_snippet(), encoding="utf-8")
    return True


def remove_path_entry(profile: Path) -> bool:
    if not profile.exists():
        return False
    lines = profile.read_text(encoding="utf-8").splitlines(keepends=True)
    kept = [line for line in lines if PATH_MARKER not in line]
    if len(kept) == len(lines):
        return False
    profile.write_text("".join(kept), encoding="utf-8")
    return True
